baseURL: "https://susimsek.github.io/"
title: Şuayb Şimşek | Blog
paginate: 5
theme: PaperMod
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
    disableXML: true
    minifyOutput: true

menu:
    main:
        - identifier: archives
          name: Archives
          url: /archives/
          weight: 10
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 20
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 30
        - identifier: search
          name: Search
          url: /search/
          weight: 40
        - identifier: gpg
          name: GPG
          url: /gpg/
          weight: 50

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: DevOpsGuy
    description: "A personal blog where I write what I've learned in Devops,Java,Golang,Blockchain and IT world"
    keywords: [DevOps, Java, Golang, Kubernetes, Blockchain, IT, Software, Developer, DevSecOps]
    author: Şuayb Şimşek
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    #POST CONFIGS
    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    assets:
        disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "/posts/gopher.png"
        favicon16x16: "/posts/gopher.png"
        favicon32x32: "/posts/gopher.png"
        apple_touch_icon: "/posts/gopher.png"
        safari_pinned_tab: "/posts/gopher.png"

    label:
        text: "Şuayb Şimşek"
        icon: /posts/gopher.png
        iconHeight: 45

    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
        title: ExampleSite
        subtitle: "This is subtitle"
        imageUrl: "<img location>"
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
        Title: "Hi! Welcome to my personal blog"
        Content: "^-^"

    socialIcons:
        - name: github
          url: "https://github.com/susimsek"
        - name: twitter
          url: "https://twitter.com/suaybsimsek58"
        - name: linkedin
          url: "https://linkedin.com/in/şuayb-şimşek-29b077178"
        - name: rss
          url: "/index.xml"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
